# Site settings
title: Costa Travel Blog
email: coolwebconfs@gmail.com
description: Travel with Costa
baseurl: "/travel-blog"
twitter_username: pcosta88
paginate: 3

# Build settings
markdown: kramdown
permalink: /:title

#Default settings
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      author: Pat
      layout: "post"
      category: Places
      comments: true
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages" # previously `post` in Jekyll 2.2.
    values:
      layout: "page"





